services:
  n8nweb:
    image: n8nio/n8n
    container_name: n8nweb
    # restart: unless-stopped
    ports:
      - ${N8N_PORT}:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=https
      - NODE_ENV=development
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    volumes:
      - ./n8n_data:/home/node/.n8n

  ollama:
    image: alpine/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /mnt/d/Projects/Docker/.ollama:/root/.ollama