version: "3.8"

services:
  n8n:
    container_name: n8nweb
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      # Konfigurasi dasar n8n
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      # URL webhook akan diganti dengan URL ngrok setelah dijalankan
      - WEBHOOK_URL=https://right-smashing-lacewing.ngrok-free.app/
      # Token bot Telegram dari BotFather
      # - TELEGRAM_ACCESS_TOKEN=123456789:ABCDEF_your_token_here
    volumes:
      - ./n8n_data:/home/node/.n8n

  ollama:
    image: alpine/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ${VOLUME_MOUNT_OLLAMA}/.ollama:/root/.ollama

  ngrok:
    container_name: ngrok
    image: docker.io/ngrok/ngrok:latest 
    restart: always
    depends_on:
      - n8n
    command: http n8n:5678 --url right-smashing-lacewing.ngrok-free.app
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    ports:
      - "4040:4040" # dashboard ngrok
